import type { Metadata } from "next";
import { TextEditorWrapper } from '@/components/TextEditorWrapper';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const inlineTextEditorConfig = {
    projectId: process.env.NEXT_PUBLIC_PROJECT_ID || 'default-project',
    enabledByDefault: false,
    showToggle: true,
    enabled: true,
    apiEndpoint: '/api/text-editor'
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TextEditorWrapper config={inlineTextEditorConfig}>

          {children}

        </TextEditorWrapper>
      </body>
    </html>
  );
}
